import { FormEvent, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { supabase, configured } from "./supabase";

type Role = "student" | "faculty" | "admin";
type View = "home" | "find" | "schedule" | "assistant";
type User = { id:string; name:string; email:string; role:Role };
type Slot = { id:string; faculty_name:string; initials:string; expertise:string; starts_at:string; ends_at:string; location:string; color:string };

const demoSlots: Slot[] = [
  {id:"1",faculty_name:"Dr. Maria Santos",initials:"MS",expertise:"Software Engineering",starts_at:"2026-08-05T09:00",ends_at:"2026-08-05T09:30",location:"CLIRDEC Consultation Room",color:"coral"},
  {id:"2",faculty_name:"Prof. Juan Dela Cruz",initials:"JD",expertise:"Data Analytics",starts_at:"2026-08-05T13:00",ends_at:"2026-08-05T13:30",location:"CLIRDEC Consultation Room",color:"blue"},
  {id:"3",faculty_name:"Dr. Ana Reyes",initials:"AR",expertise:"Research Methods",starts_at:"2026-08-06T10:00",ends_at:"2026-08-06T10:30",location:"CLIRDEC Consultation Room",color:"gold"},
  {id:"4",faculty_name:"Prof. Carlo Mendoza",initials:"CM",expertise:"Web Development",starts_at:"2026-08-07T14:00",ends_at:"2026-08-07T14:30",location:"CLIRDEC Consultation Room",color:"mint"}
];

function App(){
 const [user,setUser]=useState<User|null>(null); const [authLoading,setAuthLoading]=useState(configured);
 const [view,setView]=useState<View>("home"); const [slots,setSlots]=useState<Slot[]>(configured?[]:demoSlots);
 const [booked,setBooked]=useState<Slot[]>([]); const [selected,setSelected]=useState<Slot|null>(null);
 const [notice,setNotice]=useState(""); const [query,setQuery]=useState(""); const [menu,setMenu]=useState(false);
 const [chat,setChat]=useState<{who:"you"|"bot";text:string}[]>([{who:"bot",text:"Hi, Sofia! I use approved CLIRDEC information. Ask about services, office hours, consultation procedures, faculty availability, or official contacts."}]);
 const [question,setQuestion]=useState("");
 useEffect(()=>{
  if(!configured){setAuthLoading(false);return;}
  let active=true;
  const loadUser=async(id:string,email:string)=>{
   const {data:p,error}=await supabase.from("profiles").select("full_name,role").eq("id",id).single();
   if(!active)return;
   if(error){setNotice("Your account exists, but its portal profile could not be loaded.");setUser(null);return;}
   setUser({id,email,name:p.full_name,role:p.role as Role});
  };
  supabase.auth.getSession().then(async({data})=>{
   if(data.session)await loadUser(data.session.user.id,data.session.user.email||"");
   if(active)setAuthLoading(false);
  });
  const {data:listener}=supabase.auth.onAuthStateChange((event,session)=>{
   if(event==="SIGNED_OUT"){setUser(null);setAuthLoading(false);}
   else if(session)void loadUser(session.user.id,session.user.email||"");
  });
  return()=>{active=false;listener.subscription.unsubscribe();};
 },[]);
 useEffect(()=>{
  if(!configured||!user||user.role!=="student")return;
  void loadStudentData(user.id);
 },[user?.id,user?.role]);
 async function loadStudentData(studentId:string){
  const {data:open,error:slotError}=await supabase.from("availability").select("id,faculty_id,starts_at,ends_at,location").eq("is_open",true).order("starts_at");
  if(slotError){setNotice(slotError.message);return;}
  const facultyIds=[...new Set((open||[]).map(x=>x.faculty_id))];
  const [{data:profiles},{data:faculty}]=await Promise.all([
   supabase.from("profiles").select("id,full_name").in("id",facultyIds.length?facultyIds:["00000000-0000-0000-0000-000000000000"]),
   supabase.from("faculty_profiles").select("user_id,expertise").in("user_id",facultyIds.length?facultyIds:["00000000-0000-0000-0000-000000000000"])
  ]);
  const names=new Map((profiles||[]).map(x=>[x.id,x.full_name]));
  const expertise=new Map((faculty||[]).map(x=>[x.user_id,(x.expertise||[]).join(", ")]));
  setSlots((open||[]).map((x,i)=>{const name=names.get(x.faculty_id)||"Faculty member";return{id:x.id,faculty_name:name,initials:name.split(" ").map((n:string)=>n[0]).join("").slice(0,2),expertise:expertise.get(x.faculty_id)||"General consultation",starts_at:x.starts_at,ends_at:x.ends_at,location:x.location||"Location provided after approval",color:["coral","blue","gold","mint"][i%4]};}));
  const {data:appointments,error:appointmentError}=await supabase.from("appointments").select("availability_id,status,availability:availability_id(id,faculty_id,starts_at,ends_at,location)").eq("student_id",studentId).order("created_at",{ascending:false});
  if(appointmentError){setNotice(appointmentError.message);return;}
  const related=(appointments||[]).map((x:any)=>{const a=Array.isArray(x.availability)?x.availability[0]:x.availability;const name=names.get(a?.faculty_id)||"Faculty member";return{id:a?.id||x.availability_id,faculty_name:name,initials:name.split(" ").map((n:string)=>n[0]).join("").slice(0,2),expertise:expertise.get(a?.faculty_id)||"Consultation",starts_at:a?.starts_at,ends_at:a?.ends_at,location:a?.location||"Pending confirmation",color:"mint"};});
  setBooked(related);
 }
 const filtered=useMemo(()=>slots.filter(s=>(s.faculty_name+" "+s.expertise).toLowerCase().includes(query.toLowerCase())),[slots,query]);
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setNotice("");if(!configured){setNotice("The production database is not configured yet. Add the Supabase environment variables in Vercel.");return;}const f=new FormData(e.currentTarget);const email=String(f.get("email"));const password=String(f.get("password"));const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setNotice(error.message);}
 async function signup(e:FormEvent<HTMLFormElement>){e.preventDefault();setNotice("");if(!configured){setNotice("The production database is not configured yet. Add the Supabase environment variables in Vercel.");return;}const f=new FormData(e.currentTarget);const full_name=String(f.get("full_name"));const email=String(f.get("email"));const password=String(f.get("password"));const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name}}});if(error){setNotice(error.message);return;}setNotice(data.session?"Student account created.":"Check your email to confirm your student account, then sign in.");}
 async function logout(){if(configured)await supabase.auth.signOut();setUser(null);setView("home");}
 async function confirmBook(){if(!user||!selected)return; const slot=selected; if(configured){const {error}=await supabase.from("appointments").insert({student_id:user.id,availability_id:slot.id,topic:"General consultation",status:"pending"});if(error){setNotice(error.message);return;}} setBooked(b=>[slot,...b.filter(x=>x.id!==slot.id)]);setSelected(null);setNotice(`Request sent to ${slot.faculty_name}. An email receipt will be sent to ${user.email}; approval requires a separate faculty email.`);setView("schedule");}
 async function ask(e:FormEvent){e.preventDefault();const q=question.trim();if(!q)return;setQuestion("");setChat(c=>[...c,{who:"you",text:q}]);if(!configured){const s=q.toLowerCase();let answer="I’m not confident that I have an approved answer for that. Please choose an FAQ topic or contact authorized CLIRDEC staff for assistance.";if(s.includes("hour")||s.includes("open"))answer="CLIRDEC office hours must come from the current official office advisory. For the pilot, the knowledge-base administrator should publish the approved schedule and contact channel here.";else if(s.includes("consult")||s.includes("request")||s.includes("book"))answer="Open Faculty availability, select a faculty-approved time, describe your concern, and submit a request. The request remains pending until the faculty member approves it.";else if(s.includes("where")||s.includes("location"))answer="The consultation location or online platform is shown in the approved availability details and final faculty confirmation.";else if(s.includes("grade")||s.includes("emergency")||s.includes("complaint"))answer="I can’t answer confidential records, grades, emergencies, complaints, or academic decisions. Please use the appropriate official CLSU or CLIRDEC contact channel.";setTimeout(()=>setChat(c=>[...c,{who:"bot",text:answer}]),350);return;}try{const r=await fetch(`${import.meta.env.VITE_CHATBOT_URL||"http://localhost:8000"}/chat`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:q})});const d=await r.json();setChat(c=>[...c,{who:"bot",text:d.answer}]);}catch{setChat(c=>[...c,{who:"bot",text:"The assistant is temporarily offline. Please use the official CLIRDEC contact channel or try again later."}]);}}
 if(authLoading)return <main className="auth-loading"><p>Loading FacultyConnect…</p></main>;
 if(!user)return <ProductionAuth login={login} signup={signup} notice={notice}/>;
 if(user.role!=="student")return <RoleWorkspace user={user} logout={logout}/>;
 const nav=(next:View)=>{setView(next);setMenu(false);setNotice("");};
 return <div className="app"><header className="topbar"><button className="brand-button" onClick={()=>nav("home")}><BrandLogo/><span><b>CLSU FacultyConnect</b><small>Managed by MISO · CLIRDEC pilot</small></span></button><div className="top-actions"><button className="icon-button" aria-label="Notifications">♢<span className="dot"/></button><button className="profile-chip"><span>SN</span><i><b>{user.name}</b><small>Student</small></i></button><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">☰</button></div></header>
 <aside className={menu?"sidebar open":"sidebar"}><nav><Nav active={view==="home"} label="Overview" icon="⌂" onClick={()=>nav("home")}/><Nav active={view==="assistant"} label="Ask Consult AI" icon="✦" onClick={()=>nav("assistant")}/><Nav active={view==="find"} label="Faculty availability" icon="⌕" onClick={()=>nav("find")}/><Nav active={view==="schedule"} label="My requests" icon="□" onClick={()=>nav("schedule")}/></nav><div className="side-foot"><span>CLIRDEC</span><small>Controlled pilot · Approved content only</small><button onClick={logout}>Sign out</button></div></aside>
 <main className="content">{notice&&<div className="notice"><b>✓</b><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
 {view==="home"&&<Dashboard user={user} booked={booked} go={nav}/>} {view==="find"&&<FindFaculty query={query} setQuery={setQuery} slots={filtered} select={setSelected}/>} {view==="schedule"&&<Schedule booked={booked}/>} {view==="assistant"&&<Chat chat={chat} question={question} setQuestion={setQuestion} ask={ask}/>}</main>
 {selected&&<BookingModal slot={selected} close={()=>setSelected(null)} confirm={confirmBook}/>}</div>;
}

/* Legacy demo authentication retained temporarily for visual reference.
function Auth({role,setRole,login,notice}:{role:Role;setRole:(r:Role)=>void;login:(e:FormEvent<HTMLFormElement>)=>void;notice:string}){return <main className="auth"><section className="auth-story"><div className="public-brand"><span className="brand-mark">C</span> CLSU FacultyConnect</div><div><span className="pilot-label">MISO · CLIRDEC PILOT</span><h1>Approved answers. Clear next steps.</h1><p>Ask common CLIRDEC questions in natural language, view faculty-approved availability, and receive a safe official referral when the assistant cannot answer.</p><ul><li>Product Owner-approved FAQ knowledge</li><li>Clarification and safe staff referral</li><li>Mobile access for students and faculty</li></ul></div><small>Central Luzon State University · Nurturing a Culture of Excellence</small></section><section className="auth-panel"><form className="login" onSubmit={login}><span className="mobile-brand">CLSU FacultyConnect</span><p className="eyebrow">CONTROLLED PILOT</p><h2>Sign in to your portal</h2><p className="muted">Use demo mode to preview each role-restricted workspace.</p><div className="role-tabs">{(["student","faculty","admin"] as Role[]).map(r=><button type="button" className={role===r?"active":""} key={r} onClick={()=>setRole(r)}>{r==="admin"?"Admin":r[0].toUpperCase()+r.slice(1)}</button>)}</div><label>CLSU email address<input name="email" type="email" required defaultValue="sofia@clsu2.edu.ph"/></label><label>Password<input name="password" type="password" required minLength={6} defaultValue="password"/></label><button className="primary">Sign in <span>→</span></button>{!configured&&<small className="demo-note">Demo mode · no account required</small>}{notice&&<p className="error">{notice}</p>}</form></section></main>}
function Auth({role,setRole,login,notice}:{role:Role;setRole:(r:Role)=>void;login:(e:FormEvent<HTMLFormElement>)=>void;notice:string}){return <main className="auth"><section className="auth-story"><div className="public-brand"><span className="brand-mark">C</span> CLSU FacultyConnect</div><div><span className="pilot-label">MISO · CLIRDEC PILOT</span><h1>Approved answers. Clear next steps.</h1><p>Ask common CLIRDEC questions in natural language, view faculty-approved availability, and receive a safe official referral when the assistant cannot answer.</p><ul><li>Product Owner-approved FAQ knowledge</li><li>Clarification and safe staff referral</li><li>Mobile access for students and faculty</li></ul></div><small>Central Luzon State University · Nurturing a Culture of Excellence</small></section><section className="auth-panel"><form className="login" onSubmit={login}><span className="mobile-brand">CLSU FacultyConnect</span><p className="eyebrow">CONTROLLED PILOT</p><h2>Sign in to your portal</h2><p className="muted">Use demo mode to preview each role-restricted workspace.</p><div className="role-tabs">{(["student","faculty","admin"] as Role[]).map(r=><button type="button" className={role===r?"active":""} key={r} onClick={()=>setRole(r)}>{r==="admin"?"Admin":r[0].toUpperCase()+r.slice(1)}</button>)}</div><label>CLSU email address<input name="email" type="email" required defaultValue="sofia@clsu2.edu.ph"/></label><label>Password<input name="password" type="password" required minLength={6} defaultValue="password"/></label><button className="primary">Sign in <span>→</span></button>{!configured&&<small className="demo-note">Demo mode · no account required</small>}{notice&&<p className="error">{notice}</p>}</form></section></main>}
*/

function ProductionAuth({login,signup,notice}:{login:(e:FormEvent<HTMLFormElement>)=>void;signup:(e:FormEvent<HTMLFormElement>)=>void;notice:string}){
 const [creating,setCreating]=useState(false);
 return <main className="auth">
  <section className="auth-story">
   <div className="public-brand"><BrandLogo tone="light" size="hero"/><span>CLSU FacultyConnect</span></div>
   <div><span className="pilot-label">MISO · CLIRDEC PILOT</span><h1>Approved answers. Clear next steps.</h1><p>Use your registered email to access faculty consultation services and verified CLIRDEC guidance.</p><ul><li>Role-protected student, faculty, and administrator portals</li><li>Faculty-approved schedules and request decisions</li><li>Email updates for important appointment events</li></ul></div>
   <small>Central Luzon State University · Nurturing a Culture of Excellence</small>
  </section>
  <section className="auth-panel">
   <form className="login" onSubmit={creating?signup:login}>
    <span className="mobile-brand"><BrandLogo/><span>CLSU FacultyConnect</span></span><p className="eyebrow">SECURE PORTAL</p>
    <h2>{creating?"Create a student account":"Sign in to your portal"}</h2>
    <p className="muted">Faculty and administrator roles are assigned only through an authorized administrative process.</p>
    {creating&&<label>Full name<input name="full_name" required autoComplete="name"/></label>}
    <label>Email address<input name="email" type="email" required autoComplete="email"/></label>
    <label>Password<input name="password" type="password" required minLength={8} autoComplete={creating?"new-password":"current-password"}/></label>
    <button className="primary">{creating?"Create student account":"Sign in"} <span>→</span></button>
    <button type="button" className="text-button" onClick={()=>setCreating(x=>!x)}>{creating?"Already registered? Sign in":"New student? Create an account"}</button>
    {!configured&&<small className="demo-note">Backend setup required · Supabase environment variables are not configured.</small>}
    {notice&&<p className="error">{notice}</p>}
   </form>
  </section>
 </main>;
}
function BrandLogo({tone="dark",size="header"}:{tone?:"dark"|"light";size?:"header"|"hero"}){return <img className={`brand-logo brand-logo-${size}`} src={tone==="light"?"/brand/Logo_white.png":"/brand/Logo_Black.png"} alt="" aria-hidden="true"/>}
function Nav({active,label,icon,onClick}:{active:boolean;label:string;icon:string;onClick:()=>void}){return <button className={active?"nav-item active":"nav-item"} onClick={onClick}><span>{icon}</span>{label}</button>}
function Dashboard({user,booked,go}:{user:User;booked:Slot[];go:(v:View)=>void}){const next=booked[0];return <><section className="page-head"><div><p className="eyebrow">CLIRDEC FAQ PILOT</p><h1>What do you need help with, {user.name.split(" ")[0]}?</h1><p>Start with the approved-information assistant or view faculty-maintained availability.</p></div><button className="primary" onClick={()=>go("assistant")}>Ask Consult AI <span>→</span></button></section><section className="overview-grid"><article className="next-card"><div className="section-label"><span>LATEST CONSULTATION REQUEST</span>{next&&<b>Pending approval</b>}</div>{next?<><div className="appointment-date"><strong>{new Date(next.starts_at).getDate()}</strong><span>{new Date(next.starts_at).toLocaleDateString([], {month:"short"}).toUpperCase()}<br/>{new Date(next.starts_at).toLocaleDateString([], {weekday:"short"})}</span></div><div className="appointment-main"><span className={`avatar ${next.color}`}>{next.initials}</span><div><h3>{next.expertise}</h3><p>{next.faculty_name}</p><small>Requested time: {new Date(next.starts_at).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</small></div></div><button className="text-button" onClick={()=>go("schedule")}>View request status →</button></>:<div className="empty"><b>No active request</b><p>Availability shown in the portal is faculty-approved, but a request still requires faculty confirmation.</p></div>}</article><article className="quick-card"><span className="section-label">APPROVED GUIDANCE</span><button onClick={()=>go("assistant")}><span className="quick-icon">✦</span><i><b>Ask Consult AI</b><small>FAQs, services, procedures, hours, and contacts</small></i><strong>→</strong></button><button onClick={()=>go("find")}><span className="quick-icon">⌕</span><i><b>View faculty availability</b><small>Use approved categories and published schedules</small></i><strong>→</strong></button></article></section><section className="how"><div className="section-title"><div><p className="eyebrow">SAFE BY DESIGN</p><h2>Approved answer or official referral</h2></div><p>The pilot does not provide unrestricted generative answers.</p></div><div className="steps"><article><b>01</b><span>✦</span><h3>Ask naturally</h3><p>Use English, Filipino, mixed language, or common abbreviations.</p></article><article><b>02</b><span>?</span><h3>Clarify when needed</h3><p>The assistant asks one clarifying question when confidence is low.</p></article><article><b>03</b><span>↗</span><h3>Refer safely</h3><p>Unsupported or sensitive concerns go to an official staff channel.</p></article></div></section></>}
function FindFaculty({query,setQuery,slots,select}:{query:string;setQuery:(s:string)=>void;slots:Slot[];select:(s:Slot)=>void}){return <><section className="page-head compact"><div><p className="eyebrow">APPROVED CONSULTATION GUIDANCE</p><h1>Faculty availability</h1><p>Browse faculty-maintained schedules and approved expertise categories. The system does not automatically assign a faculty member.</p></div></section><div className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search an approved category or faculty name"/></div><div className="result-head"><b>{slots.length} published availability entries</b><span>Source: faculty-approved CLIRDEC schedules</span></div><section className="faculty-grid">{slots.map(s=><article className="faculty-card" key={s.id}><div className="faculty-top"><span className={`avatar large ${s.color}`}>{s.initials}</span><div><span className="available">● Faculty-published</span><h3>{s.faculty_name}</h3><p>{s.expertise}</p></div></div><div className="slot-line"><span>Published time</span><b>{new Date(s.starts_at).toLocaleDateString([], {weekday:"short",month:"short",day:"numeric"})} · {new Date(s.starts_at).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</b></div><button className="primary wide" onClick={()=>select(s)}>Review and request →</button></article>)}</section></>}
function Schedule({booked}:{booked:Slot[]}){return <><section className="page-head compact"><div><p className="eyebrow">CONSULTATION GUIDANCE</p><h1>My requests</h1><p>Requests shown here are not appointments until the faculty member confirms them.</p></div></section><div className="scope-note"><b>Email notifications enabled</b><span>Gmail or the registered CLSU email receives a receipt, faculty decision, schedule change, cancellation, and approved reminder. Full self-service cancellation and rescheduling remain deferred.</span></div><div className="schedule-list">{booked.map(s=><article key={s.id}><div className="date-block"><strong>{new Date(s.starts_at).getDate()}</strong><span>{new Date(s.starts_at).toLocaleDateString([], {month:"short"})}</span></div><span className={`avatar ${s.color}`}>{s.initials}</span><div className="schedule-info"><span className="status pending">PENDING FACULTY APPROVAL</span><h3>{s.expertise}</h3><p>{s.faculty_name} · Requested {new Date(s.starts_at).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</p><small>✉ Email updates enabled · Final location follows faculty approval.</small></div></article>)}{!booked.length&&<div className="empty-card">You have no active consultation requests. Ask Consult AI for the approved procedure or view faculty availability.</div>}</div></>}
function Chat({chat,question,setQuestion,ask}:{chat:{who:"you"|"bot";text:string}[];question:string;setQuestion:(s:string)=>void;ask:(e:FormEvent)=>void}){return <><section className="page-head compact"><div><p className="eyebrow">PRIMARY MVP CAPABILITY</p><h1>Ask Consult AI</h1><p>Answers use Product Owner- or CLIRDEC-approved information. Unsupported and sensitive questions receive a safe referral.</p></div></section><div className="assistant-safety"><span>✓ Approved FAQ knowledge</span><span>✓ English, Filipino, or mixed phrasing</span><span>✓ Safe fallback and staff referral</span></div><section className="chatbot"><div className="chat-head"><span className="ai-mark">✦</span><div><b>Consult AI</b><small>Online · Approved CLIRDEC knowledge base</small></div></div><div className="messages">{chat.map((m,i)=><p key={i} className={m.who}>{m.text}</p>)}</div><div className="prompts"><button onClick={()=>setQuestion("What are CLIRDEC office hours?")}>Office hours</button><button onClick={()=>setQuestion("How do I request a faculty consultation?")}>Request consultation</button><button onClick={()=>setQuestion("Where are sessions held?")}>Session location</button><button onClick={()=>setQuestion("What services are available?")}>CLIRDEC services</button></div><form onSubmit={ask}><input aria-label="Chat question" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask in English, Filipino, or mixed language..."/><button className="primary">Send →</button></form><footer className="chat-source">Answers must be traceable to an approved FAQ, office advisory, service directory, or faculty-maintained schedule.</footer></section></>}
function BookingModal({slot,close,confirm}:{slot:Slot;close:()=>void;confirm:()=>void}){return <div className="modal-backdrop" onMouseDown={close}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><p className="eyebrow">CONSULTATION REQUEST</p><h2>Request a published time</h2><div className="modal-faculty"><span className={`avatar large ${slot.color}`}>{slot.initials}</span><div><h3>{slot.faculty_name}</h3><p>{slot.expertise}</p></div></div><div className="booking-details"><div><span>Preferred date</span><b>{new Date(slot.starts_at).toLocaleDateString([], {weekday:"long",month:"long",day:"numeric"})}</b></div><div><span>Preferred time</span><b>{new Date(slot.starts_at).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</b></div><div><span>Availability source</span><b>Faculty-maintained schedule</b></div></div><label className="topic">Consultation topic and concern<textarea required placeholder="Provide enough context for the faculty member to review your request"/></label><button className="primary wide" onClick={confirm}>Submit request →</button><small className="modal-note">Submitting does not confirm an appointment. The faculty member must review and approve the request.</small></section></div>}
type FView="fhome"|"requests"|"availability"|"fprofile"; type AView="ahome"|"users"|"appointments"|"knowledge"|"reports";
const requestData=[{name:"Sofia Navarro",topic:"Software testing strategy",course:"COMSCI 3100",time:"Aug 5 · 9:00 AM"},{name:"Marcus Lim",topic:"Database normalization",course:"IT 3210",time:"Aug 6 · 1:00 PM"},{name:"Lea Ramos",topic:"Research methodology",course:"COMSCI 3100",time:"Aug 7 · 10:30 AM"}];
function RoleWorkspace({user,logout}:{user:User;logout:()=>void}){const faculty=user.role==="faculty";const [view,setView]=useState<FView|AView>(faculty?"fhome":"ahome");const [menu,setMenu]=useState(false);const nav=faculty?[["fhome","Overview","⌂"],["requests","Requests","✓"],["availability","Availability","□"],["fprofile","Profile","○"]]:[["ahome","Pilot overview","⌂"],["knowledge","FAQ knowledge base","✦"],["users","Users and roles","○"],["appointments","Consultation logs","□"],["reports","Pilot QA","▥"]];return <div className="app role-app"><header className="topbar"><button className="brand-button" onClick={()=>setView(faculty?"fhome":"ahome")}><BrandLogo/><span><b>CLSU FacultyConnect</b><small>Managed by MISO · CLIRDEC pilot</small></span></button><div className="top-actions"><button className="icon-button">♢<span className="dot"/></button><button className="profile-chip"><span>{faculty?"MS":"MA"}</span><i><b>{user.name}</b><small>{faculty?"Faculty":"Authorized administrator"}</small></i></button><button className="menu-button" onClick={()=>setMenu(!menu)}>☰</button></div></header><aside className={menu?"sidebar open":"sidebar"}><div><p className="side-kicker">{faculty?"FACULTY PORTAL":"AUTHORIZED CONTENT ADMIN"}</p><nav>{nav.map(([v,l,i])=><Nav key={v} active={view===v} label={l} icon={i} onClick={()=>{setView(v as FView|AView);setMenu(false)}}/>)}</nav></div><div className="side-foot"><span>Central Luzon State University</span><small>Role-restricted controlled pilot</small><button onClick={logout}>Sign out</button></div></aside><main className="content">{faculty?<FacultyPages view={view as FView}/>:<AdminPages view={view as AView}/>}</main></div>}
function Head({label,title,copy,action}:{label:string;title:string;copy:string;action?:string}){return <section className="page-head portal-head"><div><p className="eyebrow">{label}</p><h1>{title}</h1><p>{copy}</p></div>{action&&<button className="primary">{action} →</button>}</section>}
function Stats({data}:{data:string[][]}){return <div className="metrics">{data.map(x=><article key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></article>)}</div>}
function FacultyPages({view}:{view:FView}){const [requests,setRequests]=useState(requestData);const [slots,setSlots]=useState(["Mon-09","Tue-13","Wed-10","Thu-14","Fri-09"]);if(view==="fhome")return <><Head label="FACULTY PORTAL" title="Good afternoon, Dr. Santos" copy="Manage your consultations and availability from one place." action="Manage availability"/><Stats data={[["3","Sessions this week"],["2","Pending requests"],["24","Students assisted"],["4.8","Average rating"]]}/><div className="workspace-grid"><Work title="Upcoming consultations">{requestData.slice(0,2).map(r=><Line key={r.name} a={r.time} b={r.topic} c={r.name}/>)}</Work><Work title="Weekly availability"><div className="mini-week">{["Mon","Tue","Wed","Thu","Fri"].map((d,i)=><div key={d}><b>{d}</b><span>{i===1?"No slots":`${i+1} open`}</span></div>)}</div><div className="insight"><b>MISO tip</b><p>Your Wednesday slots fill fastest. Consider adding another afternoon time.</p></div></Work></div></>;
if(view==="requests")return <><Head label="FACULTY PORTAL" title="Appointment requests" copy="Review student concerns before accepting a consultation. The student receives your decision by email."/><div className="filter-tabs"><button className="active">Pending {requests.length}</button><button>Approved</button><button>Completed</button></div><div className="request-list">{requests.map(r=><article key={r.name}><div className="request-main"><span className="avatar mint">{r.name.split(" ").map(x=>x[0]).join("")}</span><div><span className="status pending">PENDING</span><h3>{r.topic}</h3><p>{r.name} · {r.course}</p></div><b className="request-time">{r.time}</b></div><div className="student-note"><span>Student note</span><p>Needs guidance and feedback before continuing the project.</p></div><div className="request-actions"><button className="outline" onClick={()=>setRequests(x=>x.filter(y=>y.name!==r.name))}>Decline + email</button><button className="primary" onClick={()=>setRequests(x=>x.filter(y=>y.name!==r.name))}>Accept + email ✓</button></div></article>)}{!requests.length&&<div className="empty-card">All requests have been reviewed. Email decisions were queued for delivery.</div>}</div></>;
if(view==="availability")return <><Head label="FACULTY PORTAL" title="Manage availability" copy="Select when students may request a consultation." action="Save changes"/><Work title="Weekly schedule"><div className="availability-grid"><b>Time</b>{["Mon","Tue","Wed","Thu","Fri"].map(d=><b key={d}>{d}</b>)}{["09","10","11","13","14","15"].flatMap(t=>[<span key={t}>{Number(t)>12?Number(t)-12:Number(t)}:00 {Number(t)>11?"PM":"AM"}</span>,...["Mon","Tue","Wed","Thu","Fri"].map(d=>{const k=`${d}-${t}`,on=slots.includes(k);return <button key={k} className={on?"slot-toggle selected":"slot-toggle"} onClick={()=>setSlots(s=>on?s.filter(x=>x!==k):[...s,k])}>{on?"✓":""}</button>})])}</div><p className="availability-foot"><b>{slots.length}</b> weekly slots selected</p></Work></>;
return <><Head label="FACULTY PORTAL" title="Faculty profile" copy="Help students find the appropriate faculty expert." action="Edit profile"/><section className="profile-layout"><article className="profile-summary"><span className="avatar profile-avatar coral">MS</span><h2>Dr. Maria Santos</h2><p>Associate Professor</p><span className="rating">★ 4.8 · 67 reviews</span></article><article className="profile-details"><Info l="CLSU email" v="maria.santos@clsu.edu.ph"/><Info l="College / Office" v="College of Engineering · CLIRDEC"/><Info l="Areas of expertise" v="Software Engineering, Systems Analysis, Human–Computer Interaction"/><Info l="Consultation location" v="CLIRDEC Consultation Room"/><Info l="About" v="Faculty researcher focused on usable and reliable information systems."/></article></section></>}
function AdminPages({view}:{view:AView}){const [users,setUsers]=useState([{name:"Sofia Navarro",id:"22-1045",role:"Student",status:"Active"},{name:"Dr. Maria Santos",id:"F-0182",role:"Faculty",status:"Active"},{name:"Marcus Lim",id:"22-1178",role:"Student",status:"Active"},{name:"Prof. Juan Dela Cruz",id:"F-0210",role:"Faculty",status:"Inactive"}]);const [faqs,setFaqs]=useState(["How do I book a consultation?","Where are CLIRDEC sessions held?","Can I cancel an appointment?"]);if(view==="ahome")return <><Head label="MISO ADMINISTRATION" title="Pilot overview" copy="Monitor the CLIRDEC pilot before university-wide expansion." action="Export summary"/><Stats data={[["215","Registered users"],["42","Consultations"],["8","Pending requests"],["0","Double bookings"]]}/><div className="workspace-grid"><Work title="Today’s appointments">{requestData.map(r=><Line key={r.name} a={r.time} b={r.topic} c={r.name}/>)}</Work><Work title="Recent activity"><Line a="10 min ago" b="Availability updated" c="Dr. Maria Santos"/><Line a="24 min ago" b="New consultation booked" c="Sofia Navarro"/><Line a="1 hr ago" b="FAQ entry revised" c="MISO Administrator"/></Work></div></>;
if(view==="users")return <><Head label="MISO ADMINISTRATION" title="Manage users" copy="Review pilot accounts and role assignments." action="Add user"/><div className="search-box compact-search"><span>⌕</span><input placeholder="Search by name or CLSU ID"/></div><Data headings={["User","CLSU ID","Role","Status","Action"]}>{users.map(u=><div className="data-row" key={u.id}><span data-label="User"><b>{u.name}</b></span><span data-label="CLSU ID">{u.id}</span><span data-label="Role">{u.role}</span><span data-label="Status"><i className={u.status==="Active"?"active-pill":"inactive-pill"}>{u.status}</i></span><span data-label="Action"><button className="table-action" onClick={()=>setUsers(x=>x.filter(y=>y.id!==u.id))}>Remove</button></span></div>)}</Data></>;
if(view==="appointments")return <><Head label="MISO ADMINISTRATION" title="Manage appointments" copy="Monitor schedules and investigate pilot exceptions." action="Export list"/><div className="filter-tabs"><button className="active">All 42</button><button>Confirmed 31</button><button>Pending 8</button><button>Cancelled 3</button></div><Data headings={["Consultation","Participants","Date and time","Status"]} cls="appointment-row">{requestData.map((r,i)=><div className="data-row appointment-row" key={r.name}><span data-label="Consultation"><b>{r.topic}</b><small>{r.course}</small></span><span data-label="Participants">{r.name}<small>Dr. Maria Santos</small></span><span data-label="Date and time">{r.time}</span><span data-label="Status"><i className={i===1?"pending-pill":"active-pill"}>{i===1?"Pending":"Confirmed"}</i></span></div>)}</Data></>;
if(view==="knowledge")return <><Head label="AUTHORIZED CONTENT ADMIN" title="FAQ knowledge base" copy="Only approved CLIRDEC information may be published to the NLP assistant." action="Add draft entry"/><div className="scope-note"><b>Approval rule</b><span>New or edited answers remain drafts until the Product Owner or designated CLIRDEC approving officer approves publication. Administrative changes require an audit record.</span></div><div className="knowledge-layout"><Work title="Draft an answer"><div className="knowledge-form"><label>Student question<input placeholder="Enter a frequently asked question"/></label><label>Approved source<input placeholder="Official page, advisory, procedure, or faculty schedule"/></label><label>Proposed answer<textarea placeholder="Write the verified response"/></label><label>Category<select><option>Office hours and contacts</option><option>Consultation procedure</option><option>Faculty availability</option><option>CLIRDEC services</option></select></label><button className="primary">Save as draft</button></div></Work><Work title="Knowledge review queue"><div className="faq-list">{faqs.map((f,i)=><article key={f}><span>{i===0?"Approved":"Review"}</span><b>{f}</b><button onClick={()=>setFaqs(x=>x.filter(y=>y!==f))}>Archive</button></article>)}</div></Work></div></>;
return <><Head label="PILOT ACCEPTANCE" title="QA and user-acceptance testing" copy="Track provisional thresholds that still require Product Owner confirmation." action="Export QA evidence"/><Stats data={[["80%","FAQ accuracy target"],["≤3s","Response-time target"],["80%","Task completion target"],["4/5","Satisfaction target"]]}/><div className="report-grid"><Work title="Required pilot checks"><div className="qa-list"><p><b>FAQ test set</b><span>Approved questions, supported paraphrases, and official source traceability</span></p><p><b>Safe fallback</b><span>Clarification, suggested topics, and staff referral for unsupported questions</span></p><p><b>Role separation</b><span>Student, faculty, and administrator permissions remain distinct</span></p><p><b>Availability integrity</b><span>Only faculty-approved schedules are shown; no invented confirmed booking</span></p></div></Work><Work title="Acceptance gate"><div className="qa-list"><p><b>No critical security or privacy defect</b><i>Required</i></p><p><b>No unresolved high-severity error</b><i>Required</i></p><p><b>Representative students and faculty tested</b><i>Pending</i></p><p><b>Product Owner threshold confirmation</b><i>Open question</i></p></div></Work></div></>}
function Work({title,children}:{title:string;children:ReactNode}){return <section className="work-card"><div className="card-title"><h2>{title}</h2></div>{children}</section>}
function Line({a,b,c}:{a:string;b:string;c:string}){return <div className="timeline-line"><span>{a}</span><i/><p><b>{b}</b><small>{c}</small></p></div>}
function Info({l,v}:{l:string;v:string}){return <div className="info"><span>{l}</span><p>{v}</p></div>}
function Data({headings,children,cls=""}:{headings:string[];children:ReactNode;cls?:string}){return <section className="data-card"><div className={`data-row data-head ${cls}`}>{headings.map(h=><b key={h}>{h}</b>)}</div>{children}</section>}
export default App;
